### ISSUE TITLE
No module named 'arg_parser'

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/ebStruct#19]
Hi, I have followed the installation steps, but when I run "GenomonSV parse", it showed the following error:

```
Traceback (most recent call last):
  File "/bins/miniconda3/envs/np_qc/bin/GenomonSV", line 5, in <module>
    from genomon_sv import main
  File "/bins/miniconda3/envs/np_qc/lib/python3.6/site-packages/genomon_sv/__init__.py", line 3, in <module>
    from arg_parser import create_parser
ModuleNotFoundError: No module named 'arg_parser'
```

Could you tell me how to fix this? Thanks!

**Comment by ken0-1n** [comment]
Hi, thank you for your interest in GenomonSV.

I have tested the latest GenomonSV after cloning it with git clone and did not get the ModuleNotFoundError.
- The build number: fe19f08f5c1f67da954e12e735c1e7f925150d83.

Please try again using the latest version of GenomonSV.
If you have any errors or questions, please let me know.

**Comment by charliechen912ilovbash** [comment]
Thanks for your reply! I found out that the Ubuntu version could be one of the reason caused this error.
I first installed GenomonSV in the latest version of Ubuntu (probably is 20.04) with singularity, then I tried to installed 16.04 as the Dockerfile and everything seems good. Maybe it's because of the version of python, I'm not pretty sure.


> Hi, thank you for your interest in GenomonSV.
> 
> I have tested the latest GenomonSV after cloning it with git clone and did not get the ModuleNotFoundError.
> 
> * The build number: [fe19f08](https://github.com/Genomon-Project/GenomonSV/commit/fe19f08f5c1f67da954e12e735c1e7f925150d83).
> 
> Please try again using the latest version of GenomonSV.
> If you have any errors or questions, please let me know.

**Comment by charliechen912ilovbash** [comment]
By the way, it will be very helpful if you could provide some example commands to complete the full GenomonSV pipeline, including normal and tumor sample groups. Moreover, how do the gene.bed and exon.bed files look like, could you provides some examples? Thank you!

**Comment by charliechen912ilovbash** [comment]
In the "GenomonSV filt" step, you mentioned the "annotation_dir", but there seems no this option?

**Comment by ken0-1n** [comment]
Hi, sorry for the late response, and thank you for the information that GenomonSV does not work with the latest version of Ubuntu in Dockerfile.
I'm glad to hear that GenomonSV worked.

>By the way, it will be very helpful if you could provide some example commands to complete the full GenomonSV pipeline, including normal and tumor sample groups. 

We provide the example commands to complete the full GenomonSV pipeline.

```
# Step 1 parse

GenomonSV \
    parse \
    ${INPUT_BAM} \
    ${OUTPUT_DIR}/${SAMPLE}
    
# Step 2 make control_info.txt (manual)

cat ${CONTROL_NAME}.control_info.txt
SampleNormal1	${OUTPUT_DIR}/SampleNormal1
SampleNormal2	${OUTPUT_DIR}/SampleNormal2
SampleNormal3	${OUTPUT_DIR}/SampleNormal3
SampleNormal4	${OUTPUT_DIR}/SampleNormal4
SampleNormal5	${OUTPUT_DIR}/SampleNormal5
...(omitted)...
SampleNormalN	${OUTPUT_DIR}/SampleNormalN

# Step 3 merge
    
GenomonSV \
    merge \
    ${CONTROL_NAME}.control_info.txt \
    ${CONTROL_NAME}.merged.junction.control.bedpe.gz 

# Step 4 filt

GenomonSV \
    filt \
    ${TUMOR_BAM} \
    ${TUMOR_SV_DIR}/${TUMOR_SAMPLE} \
    ${REFERENCE} \
    --matched_control_bam ${NORMAL_BAM} \
    --matched_control_label ${NORMAL_SAMPLE} \
    --non_matched_control_junction {CONTROL_NAME}.merged.junction.control.bedpe.gz \
    --min_junc_num 2 --max_control_variant_read_pair 10 --min_overhang_size 30
    
# Step 5 sv_utils filt (additional)

sv_utils \
    filter \
    ${TUMOR_SV_DIR}/${TUMOR_SAMPLE}.genomonSV.result.txt \
    ${TUMOR_SV_DIR}/${TUMOR_SAMPLE}.genomonSV.result.filt.txt \
    --min_tumor_allele_freq 0.07 --max_control_variant_read_pair 1 --control_depth_thres 10 --inversion_size_thres 1000
```

**Comment by ken0-1n** [comment]
> Moreover, how do the gene.bed and exon.bed files look like, could you provides some examples? Thank you!

Please install annot_utils, and then the gene.bed and exon.bed files will be downloaded and prepared automatically. Users don't need to worry about entering these files. So the annotation_dir option is no longer needed.

```
pip install annot_utils
```

We have removed the annotation_dir option.
We will try to brush up the documents...
